In [4]:
import numpy as np
np.arange(1,10).reshape((3,3)) # size of original array must match the size of the reshaped array)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
import numpy as npp 
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [8]:
x.shape

(5,)

In [16]:
x.reshape((1,5))

array([[0, 1, 2, 3, 4]])

In [18]:
x[:, np.newaxis]#column vector using newaxis

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [22]:
x[np.newaxis,:]#row vector using newaxis

array([[0, 1, 2, 3, 4]])

In [24]:
"np.concatenate, np.vstack, np.hstack"
x=np.array([1,2,3])
y=np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [28]:
z=[7,8,9]
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr1 = np.array([
    [1,2,3],
    [4,5,6],
])
np.concatenate([arr1,arr1])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [32]:
np.concatenate([arr1,arr1], axis = 1) #concatenate 2-dim array along second axis, axis 1=>colum

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [36]:
#np.vstack 
np.vstack([x,arr1])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [40]:
#np.hstack
y=([
    [99,44],
    [33,22]
])
np.hstack([y,arr1])

array([[99, 44,  1,  2,  3],
       [33, 22,  4,  5,  6]])

In [44]:
#np.split, np.hsplit, np.vsplit
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split (x,[3,5]) #np.split(array, list of indices split points)
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [46]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
#np.vsplit
upper, lower = np.vsplit (grid, [2]) #array, split index
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [50]:
#np.hsplit
left,right = np.hsplit(grid,[2])
print (left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
