In [2]:
import math
A = 16
print (math.sqrt(A))

4.0


In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
from math import sqrt, sin
A = 16
B = 3.14
print(sqrt(A))
print(sin(B))

4.0
0.0015926529164868282


In [6]:
pip install Matplotlib

Note: you may need to restart the kernel to use updated packages.


In [8]:
pip install Panda

  Preparing metadata (setup.py) ... done
  Created wheel for Panda: filename=panda-0.3.1-py3-none-any.whl size=7239 sha256=d8c90880a7b1d6493daefd3ce1285d9b4efc8f7c569286113bce2d8b63fce3da
  Stored in directory: /Users/nsherpa/Library/Caches/pip/wheels/98/41/5b/6ca54e0b6a35e1b7248c12f56fcb753dfb7717fefaa0fb45f5
Successfully built Panda
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install Matplotlib

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
np.__version__

'1.26.4'

In [6]:
my_arr = np.array([2,4,8,16])
print(my_arr)
print(type(my_arr)) #data type is ndarray

[ 2  4  8 16]
<class 'numpy.ndarray'>


In [10]:
np.array([1,2.4,3,5])

array([1. , 2.4, 3. , 5. ])

In [12]:
np.array(['mystr',2.4,3,5]) #converts all to string data type

array(['mystr', '2.4', '3', '5'], dtype='<U32')

In [30]:
np.array([1.25, 3,4,5], dtype = 'int16')

array([1, 3, 4, 5], dtype=int16)

In [32]:
import numpy as np
np. array ([
            [1,2,3],
            [4,5,6],
            [7,8,9],
]) 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
import numpy as np

x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

print(x[1][2])

6


In [40]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [44]:
np.ones((3,5,2), dtype = int)
# 3 is dimension, 5 is row, 5 is column

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [46]:
np.arange (1,31,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [48]:
np.linspace(0,1,5) #for linear spacing between numbers

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [50]:
np.random.random((3,3)) #random number between 0 and 1....create 3*3 array of uniformly distributed random)

array([[0.46532686, 0.35330397, 0.82215977],
       [0.66049033, 0.21171403, 0.8325111 ],
       [0.54309176, 0.02088331, 0.48378862]])

In [52]:
np.random.normal(0,1, (3,3)) #create a 3*3 array of normally distributes random values with mean 0 and 1

array([[ 0.22421017,  0.94987103,  0.38372232],
       [-0.54339244,  0.82495711, -0.06497564],
       [ 0.58368485,  0.75380686, -0.33065156]])