In [2]:
import numpy as np
x = np.array([3,4,-3,0,8])
np.sort(x)

array([-3,  0,  3,  4,  8])

In [4]:
x = np.array([2,3,-2,7,0])
np.argsort(x) #returns the indices of sorted elements

array([2, 4, 0, 1, 3])

In [6]:
rand = np.random.RandomState(42)
x = rand.randint(0,10,(4,6))
x

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [20]:
import numpy as np

name = ["alice", "nob", "cathy", "steve"]
age = [35, 42, 25, 15]
weight = [60.3, 80.2, 75.1, 42.4]

# Define the structured array with proper dtype
data = np.zeros(4, dtype=[('name', 'U10'), ('age', 'i8'), ('weight', 'f8')])

# Assign the data
data['name'] = name
data['age'] = age
data['weight'] = weight

data.dtype
print(data)

#U10 : Unicode string of max length
#i4: 4-byte integer
#f8: 8-byte float

[('alice', 35, 60.3) ('nob', 42, 80.2) ('cathy', 25, 75.1)
 ('steve', 15, 42.4)]


In [22]:
data['name']

array(['alice', 'nob', 'cathy', 'steve'], dtype='<U10')

In [24]:
data[0]

('alice', 35, 60.3)

In [32]:
data[0]['name'] = 'Michael'

In [34]:
data[0]

('Michael', 35, 60.3)