In [24]:
import numpy as np
np.random.random((3,2))

array([[0.45735224, 0.88832154],
       [0.62982093, 0.71849673],
       [0.73589967, 0.61270609]])

In [30]:
np.random.randint(0, 4, (5,5))

array([[3, 2, 1, 0, 2],
       [3, 1, 3, 1, 1],
       [3, 3, 1, 3, 1],
       [2, 2, 2, 3, 1],
       [3, 2, 1, 0, 1]])

In [42]:
import numpy as np
np.random.randint(0, 4, (5, 5))

array([[2, 3, 3, 0, 1],
       [1, 1, 0, 1, 1],
       [2, 1, 1, 3, 3],
       [2, 3, 2, 2, 1],
       [0, 0, 2, 1, 1]])

In [54]:
x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (4,3))
x3 = np.random.randint(10, size = (2,3,4))
print(x1)
print(x2)
print(x3)


[2 6 9 9 0 3]
[[6 4 9]
 [2 9 6]
 [8 4 8]
 [6 7 9]]
[[[2 8 4 6]
  [8 6 3 7]
  [4 2 0 3]]

 [[6 8 3 0]
  [9 7 5 0]
  [4 3 0 7]]]


In [56]:
print(x1.ndim)
print(x2.ndim)
print(x3.ndim)

1
2
3


In [58]:
print(x1.shape) #show the number of rows and columns)
print(x2.shape)
print(x3.shape)

(6,)
(4, 3)
(2, 3, 4)


In [75]:
y = np.random.randint(0, 10, (5, 2))
print(y.shape)

(5, 2)


In [85]:
y.dtype

dtype('int64')

In [89]:
print("y.itemsize =", y.itemsize)
print("x3.itemsize =", x3.itemsize)


y.itemsize = 8
x3.itemsize = 8


In [91]:
x1.nbytes == x1.itemsize * x1.size #This code is comparing two values related to the memory usage of a NumPy array (x1):

True

In [97]:
import numpy as np
np.random.randint(0, 10, (5,5))

array([[2, 6, 1, 3, 2],
       [3, 8, 8, 1, 7],
       [7, 5, 4, 0, 5],
       [3, 4, 2, 8, 7],
       [1, 7, 7, 2, 6]])

In [101]:
import numpy as np
arr = np.random.randint(0, 10, (5,5))
print (arr)
print (arr[0,0])
print(arr[2, -1])

[[8 6 3 1 5]
 [5 8 6 5 9]
 [8 9 4 7 0]
 [3 3 2 1 9]
 [7 0 3 0 9]]
8
0


In [103]:
print(arr[-1, 2])

3


In [113]:
arr[2, -1] = 3.14
print (arr)

[[8 6 3 1 5]
 [5 8 6 5 9]
 [8 9 4 7 3]
 [3 3 2 1 9]
 [7 0 3 0 9]]


In [143]:
arr = np.random.randint(0, 10, (5, 5)).astype(float) # Create an array of integers, but explicitly cast it to float
arr[2, -1] = 3.14
arr

array([[9.  , 4.  , 1.  , 1.  , 4.  ],
       [4.  , 7.  , 7.  , 5.  , 6.  ],
       [5.  , 2.  , 8.  , 8.  , 3.14],
       [6.  , 2.  , 7.  , 9.  , 3.  ],
       [3.  , 9.  , 7.  , 2.  , 5.  ]])

In [153]:
new = np.array([
    [3,5,2],
    [2,3,6],
    [5,7,1]
])
new

array([[3, 5, 2],
       [2, 3, 6],
       [5, 7, 1]])

In [22]:
import numpy as np
new = np.array([
    [3,5,2],
    [2,3,6],
    [5,7,1]
])
new
new.max(axis=0)


array([5, 7, 6])

In [26]:
#unique for not double value
arr = [1, 2, 3, 4, 3, 2, 1]
unique_arr = list(set(arr))
print(unique_arr)

[1, 2, 3, 4]
