In [20]:
import numpy as np
import pandas as pd

seattle = pd.read_csv('Seattle2014.csv')

print(seattle[::-1].head())

               STATION                                STATION_NAME      DATE  \
364  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141231   
363  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141230   
362  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141229   
361  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141228   
360  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141227   

     PRCP  SNWD  SNOW  TMAX  TMIN  AWND  WDF2  WDF5  WSF2  WSF5  WT01  WT05  \
364     0     0     0    33   -27    30    30 -9999    58 -9999 -9999 -9999   
363     0     0     0    33   -21    36    90    70    63    76 -9999 -9999   
362     0     0     0    61     6    43   350   350    76   103     1 -9999   
361    41     0     0    67    28    18    50    30    58    72     1 -9999   
360    33     0     0    94    44    49   210   210   112   161     1 -9999   

     WT02  WT03  
364 -9999 -9999  
363 -999

In [26]:
import numpy as np
import pandas as pd

weather = pd.read_csv('weather.csv')

print(weather[::-1].head())

            date  precipitation  temp_max  temp_min  wind weather
1460  2015-12-31            0.0       5.6      -2.1   3.5     sun
1459  2015-12-30            0.0       5.6      -1.0   3.4     sun
1458  2015-12-29            0.0       7.2       0.6   2.6     fog
1457  2015-12-28            1.5       5.0       1.7   1.3    rain
1456  2015-12-27            8.6       4.4       1.7   2.9    rain


In [40]:
weather.shape

(1461, 6)

In [36]:
weather.describe

<bound method NDFrame.describe of             date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]>

In [44]:
weather.info

<bound method DataFrame.info of             date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]>

In [6]:
import numpy as np
import pandas as pd

# Reading the CSV file
weather = pd.read_csv('weather.csv')

# Selecting the first 5 columns
first_five_columns = weather.iloc[:, :5]

# Reversing the rows and displaying the first 5 rows
print(first_five_columns[::-1].head())

# Handling non-numeric values: Coerce errors while calculating mean
# This will turn non-numeric data into NaN, and then calculate the mean of numeric columns.
mean_values = first_five_columns.apply(pd.to_numeric, errors='coerce').mean()

print("\nMean of the first 5 columns:\n", mean_values)


            date  precipitation  temp_max  temp_min  wind
1460  2015-12-31            0.0       5.6      -2.1   3.5
1459  2015-12-30            0.0       5.6      -1.0   3.4
1458  2015-12-29            0.0       7.2       0.6   2.6
1457  2015-12-28            1.5       5.0       1.7   1.3
1456  2015-12-27            8.6       4.4       1.7   2.9

Mean of the first 5 columns:
 date                   NaN
precipitation     3.029432
temp_max         16.439083
temp_min          8.234771
wind              3.241136
dtype: float64


In [12]:
weather.describe(include = "all")
#count: The total number of non-null entries for each column. For example, the dataset has 1461 records for each variable like precipitation, temp_max, temp_min, wind, etc.

#unique: This applies to categorical data, like weather, showing how many unique values are present. The weather column has 5 unique weather types (e.g., rain, clear, etc.).

#top: The most frequent value in categorical columns. For instance, the most common date is 2012-01-01, and the most frequent weather condition is rain.

#freq: The frequency of the most common value. For weather, "rain" occurs 641 times.

#mean: The average value of numerical columns. For example, the average precipitation is 3.03, the average temp_max is 16.44°C, and the average temp_min is 8.23°C.

#std (standard deviation): The spread of the data around the mean. A higher standard deviation means the data points are more spread out. For example, precipitation has a standard deviation of 6.68, meaning precipitation values vary widely.

#min/max: The minimum and maximum values. The lowest recorded temp_min is -7.1°C, while the highest recorded temp_max is 35.6°C.

#25%, 50%, 75%: These are the quartiles, which divide the data into four equal parts. For example, 25% of temp_max values are below 10.6°C, 50% are below 15.6°C (the median), and 75% are below 22.2°C.


date  precipitation     temp_max     temp_min         wind  \
count         1461    1461.000000  1461.000000  1461.000000  1461.000000   
unique        1461            NaN          NaN          NaN          NaN   
top     2012-01-01            NaN          NaN          NaN          NaN   
freq             1            NaN          NaN          NaN          NaN   
mean           NaN       3.029432    16.439083     8.234771     3.241136   
std            NaN       6.680194     7.349758     5.023004     1.437825   
min            NaN       0.000000    -1.600000    -7.100000     0.400000   
25%            NaN       0.000000    10.600000     4.400000     2.200000   
50%            NaN       0.000000    15.600000     8.300000     3.000000   
75%            NaN       2.800000    22.200000    12.200000     4.000000   
max            NaN      55.900000    35.600000    18.300000     9.500000   

       weather  
count     1461  
unique       5  
top       rain  
freq       641  
mean       NaN  
std        NaN  
min        NaN  
25%        NaN  
50%        NaN  
75%        NaN  
max        NaN

In [16]:
weather.info()
"""The .info() method provides a concise summary of the DataFrame, including the number of non-null entries, data types, and memory usage. Here's an example of the kind of output you would expect:"""
"""The output shows:

The total number of entries (1461 in this case).
A list of columns along with the count of non-null values.
The data types of each column (float64 for numerical data and object for categorical or textual data like dates or weather descriptions).
The memory usage of the DataFrame."""

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           1461 non-null   object 
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object 
dtypes: float64(4), object(2)
memory usage: 68.6+ KB


"The .info() method provides a concise summary of the DataFrame, including the number of non-null entries, data types, and memory usage. Here's an example of the kind of output you would expect:"

In [18]:
weather.tail()
"""This will return the last 5 rows of the dataset, showing the structure and values of the final entries. Here’s an example of how the output may look:"""


date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            8.6       4.4       1.7   2.9    rain
1457  2015-12-28            1.5       5.0       1.7   1.3    rain
1458  2015-12-29            0.0       7.2       0.6   2.6     fog
1459  2015-12-30            0.0       5.6      -1.0   3.4     sun
1460  2015-12-31            0.0       5.6      -2.1   3.5     sun

In [20]:
weather.sort_values(by=["date"])

date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [28]:
import numpy as np
x = np.array([3,4,-3,0,8])
np.sort(x)

array([-3,  0,  3,  4,  8])

In [32]:
x = np.array([2,3,-2,7,0])
np.argsort(x) #returns the indices of sorted elements

array([2, 4, 0, 1, 3])

In [40]:
rand = np.random.RandomState(42)
x = rand.randint(0,10,(4,6))
x

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [42]:
np.sort(x,axis=0) #column wise sorting

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [44]:
np.sort(x,axis=1) #row wise sorting

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [46]:
import numpy as np
x = np.array([7, 2,3,1,6,5,4])
print (x)
np.partition(x,3)

[7 2 3 1 6 5 4]


array([2, 1, 3, 4, 6, 5, 7])

In [ ]:
name = ["Alice","Bob","Cathy","Steve"]
age = [36,45,21,44]
weight = [45,99,82,19]
data = np.zeros(4,dtype ={'name' :('name', 'age', 'weight'),
                          'formats' :('U10'